FROM php:7.1.3-apache

RUN docker-php-ext-install pdo pdo_mysql

RUN apt-get update && apt-get install -y unzip

RUN a2enmod rewrite

RUN apt-get update && apt-get install -y libmemcached-dev zlib1g-dev \
	&& pecl install memcached \
	&& docker-php-ext-enable memcached

# RUN pecl install redis-3.1.1 \
#    && pecl install xdebug-2.5.1 \
#    && docker-php-ext-enable redis xdebug

COPY . /var/www

WORKDIR /var/www

RUN ./composer.phar install

#CMD ["php", "./cmd/bootstrap.php"]