FROM php:7.1.3-apache

RUN docker-php-ext-install pdo pdo_mysql

RUN apt-get update && apt-get install -y unzip

RUN a2enmod rewrite

RUN apt-get update && apt-get install -y libmemcached-dev zlib1g-dev \
	&& pecl install memcached-3.0.3 \
	&& docker-php-ext-enable memcached

COPY . /var/www

WORKDIR /var/www

RUN ./composer.phar install
